// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package eu.dime.dnsregister.entities;

import eu.dime.dnsregister.entities.Records;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Records_Roo_Configurable {
    
    declare @type: Records: @Configurable;
    
}
